version: "3.9"
services:
  redis-service:
    image: redis:alpine
    # ports:
    #   - 6379:6379
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"

  web-service:
    build: ./web
    ports:
      - "80:8000"
    environment:
      - REDIS_URL=redis://redis-service:6379
    networks:
      - backend-network
    depends_on:
      - redis-service
    command: "gunicorn page_tracker.app:app --bind 0.0.0.0:8000 --reload"
    # volumes:
    #   - ./web/src/:/home/simpleflask/src/

  test-service:
    profiles:
      - testing
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis-service:6379
      - FLASK_URL=http://web-service:8000
    networks:
      - backend-network
    depends_on:
      - redis-service
      - web-service
    command: >
      sh -c 'python -m pytest test/e2e/ -vv
      --redis-url $$REDIS_URL
      --flask-url $$FLASK_URL
      '
    # $$ to disable premature substituton of env variables
    # to interpolate those vars wrap with single quote
networks:
  backend-network:

volumes:
  redis-volume:
