version: "3.9"
services:
  redis-service:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend-network
    volumes:
      - "page-redis-volume:/data"

  web-service:
    build: ./web
    ports:
      - "80:5000"
    environment:
      - REDIS_URL="redis://redis-service:6379"
    networks:
      - backend-network
    depends_on:
      - redis-service

networks:
  backend-network:

volumes:
  redis-volume:
